ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_package_version_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_base_units_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_bonus_units_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_completed_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "package_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "package_version_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "package_version" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "package_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "base_units" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ALTER COLUMN "bonus_units" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "product_type" varchar(24) DEFAULT 'lesson_package' NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_product_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_product_version_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_product_version" integer;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_product_name" varchar(160);--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_mode" varchar(20);--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_usage_limit" integer;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_duration_unit" varchar(20);--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_duration_count" integer;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_activation_policy" varchar(24);--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "period_card_entitlement_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_period_card_product_id_period_card_products_id_fk" FOREIGN KEY ("period_card_product_id") REFERENCES "public"."period_card_products"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_period_card_product_version_id_period_card_product_versions_id_fk" FOREIGN KEY ("period_card_product_version_id") REFERENCES "public"."period_card_product_versions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_period_card_entitlement_id_period_card_entitlements_id_fk" FOREIGN KEY ("period_card_entitlement_id") REFERENCES "public"."period_card_entitlements"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "lesson_commerce_orders_period_card_entitlement_unique" ON "lesson_commerce_orders" USING btree ("period_card_entitlement_id");--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_product_snapshot_check" CHECK (("lesson_commerce_orders"."product_type" = 'lesson_package' and "lesson_commerce_orders"."package_id" is not null and "lesson_commerce_orders"."package_version_id" is not null and "lesson_commerce_orders"."package_version" > 0 and "lesson_commerce_orders"."package_name" is not null and "lesson_commerce_orders"."base_units" > 0 and "lesson_commerce_orders"."bonus_units" >= 0 and "lesson_commerce_orders"."period_card_product_id" is null and "lesson_commerce_orders"."period_card_product_version_id" is null and "lesson_commerce_orders"."period_card_product_version" is null and "lesson_commerce_orders"."period_card_product_name" is null and "lesson_commerce_orders"."period_card_mode" is null and "lesson_commerce_orders"."period_card_usage_limit" is null and "lesson_commerce_orders"."period_card_duration_unit" is null and "lesson_commerce_orders"."period_card_duration_count" is null and "lesson_commerce_orders"."period_card_activation_policy" is null) or ("lesson_commerce_orders"."product_type" = 'period_card' and "lesson_commerce_orders"."package_id" is null and "lesson_commerce_orders"."package_version_id" is null and "lesson_commerce_orders"."package_version" is null and "lesson_commerce_orders"."package_name" is null and "lesson_commerce_orders"."base_units" is null and "lesson_commerce_orders"."bonus_units" is null and "lesson_commerce_orders"."period_card_product_id" is not null and "lesson_commerce_orders"."period_card_product_version_id" is not null and "lesson_commerce_orders"."period_card_product_version" > 0 and "lesson_commerce_orders"."period_card_product_name" is not null and "lesson_commerce_orders"."period_card_mode" in ('limited','unlimited') and (("lesson_commerce_orders"."period_card_mode" = 'limited' and "lesson_commerce_orders"."period_card_usage_limit" > 0) or ("lesson_commerce_orders"."period_card_mode" = 'unlimited' and "lesson_commerce_orders"."period_card_usage_limit" is null)) and "lesson_commerce_orders"."period_card_duration_unit" in ('day','week','month') and "lesson_commerce_orders"."period_card_duration_count" > 0 and "lesson_commerce_orders"."period_card_activation_policy" in ('immediate','on_first_use')));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_completed_check" CHECK (("lesson_commerce_orders"."status" = 'completed') = ("lesson_commerce_orders"."completed_at" is not null and (("lesson_commerce_orders"."product_type" = 'lesson_package' and "lesson_commerce_orders"."grant_movement_id" is not null and "lesson_commerce_orders"."period_card_entitlement_id" is null) or ("lesson_commerce_orders"."product_type" = 'period_card' and "lesson_commerce_orders"."grant_movement_id" is null and "lesson_commerce_orders"."period_card_entitlement_id" is not null))));