ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_channel_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_payment_method_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_channel_payment_check";--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" DROP CONSTRAINT "lesson_commerce_orders_status_check";--> statement-breakpoint
ALTER TABLE "lesson_package_templates" ADD COLUMN "sale_scope" varchar(20) DEFAULT 'public' NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_package_templates" ADD COLUMN "origin_type" varchar(40);--> statement-breakpoint
ALTER TABLE "lesson_package_templates" ADD COLUMN "origin_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ADD COLUMN "sale_scope" varchar(20) DEFAULT 'public' NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ADD COLUMN "origin_type" varchar(40);--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ADD COLUMN "origin_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "source_type" varchar(32) DEFAULT 'normal' NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "source_reference_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "deposit_applied_minor" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "balance_due_minor" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD COLUMN "payment_deadline_at" timestamp with time zone;--> statement-breakpoint
UPDATE "lesson_commerce_orders" SET "balance_due_minor" = "amount_minor" WHERE "source_type" = 'normal';--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ALTER COLUMN "sale_scope" DROP DEFAULT;--> statement-breakpoint
CREATE UNIQUE INDEX "lesson_package_templates_institution_origin_unique" ON "lesson_package_templates" USING btree ("institution_id","origin_type","origin_id");--> statement-breakpoint
CREATE UNIQUE INDEX "lesson_commerce_orders_group_formation_student_unique" ON "lesson_commerce_orders" USING btree ("source_type","source_reference_id","student_id") WHERE "lesson_commerce_orders"."source_type" = 'group_formation' and "lesson_commerce_orders"."source_reference_id" is not null;--> statement-breakpoint
ALTER TABLE "lesson_package_templates" ADD CONSTRAINT "lesson_package_templates_origin_shape_check" CHECK (("lesson_package_templates"."origin_type" is null and "lesson_package_templates"."origin_id" is null) or ("lesson_package_templates"."origin_type" = 'group_formation' and "lesson_package_templates"."origin_id" is not null));--> statement-breakpoint
ALTER TABLE "lesson_package_templates" ADD CONSTRAINT "lesson_package_templates_internal_sale_check" CHECK ("lesson_package_templates"."sale_scope" <> 'internal' or not "lesson_package_templates"."online_sale_enabled");--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ADD CONSTRAINT "lesson_package_versions_origin_shape_check" CHECK (("lesson_package_versions"."origin_type" is null and "lesson_package_versions"."origin_id" is null) or ("lesson_package_versions"."origin_type" = 'group_formation' and "lesson_package_versions"."origin_id" is not null));--> statement-breakpoint
ALTER TABLE "lesson_package_versions" ADD CONSTRAINT "lesson_package_versions_internal_sale_check" CHECK ("lesson_package_versions"."sale_scope" <> 'internal' or not "lesson_package_versions"."online_sale_enabled");--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_source_check" CHECK (("lesson_commerce_orders"."source_type" = 'normal' and "lesson_commerce_orders"."source_reference_id" is null and "lesson_commerce_orders"."deposit_applied_minor" = 0) or ("lesson_commerce_orders"."source_type" = 'group_formation' and "lesson_commerce_orders"."source_reference_id" is not null));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_settlement_amount_check" CHECK ("lesson_commerce_orders"."deposit_applied_minor" >= 0 and "lesson_commerce_orders"."balance_due_minor" >= 0 and "lesson_commerce_orders"."amount_minor" = "lesson_commerce_orders"."deposit_applied_minor" + "lesson_commerce_orders"."balance_due_minor");--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_awaiting_settlement_check" CHECK ("lesson_commerce_orders"."status" <> 'awaiting_settlement' or ("lesson_commerce_orders"."source_type" = 'group_formation' and "lesson_commerce_orders"."balance_due_minor" > 0 and "lesson_commerce_orders"."channel" = 'pending'));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_channel_check" CHECK ("lesson_commerce_orders"."channel" in ('pending','online','offline'));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_payment_method_check" CHECK ("lesson_commerce_orders"."payment_method" in ('pending','wechat_pay','mock','cash','bank_transfer','wechat_transfer','other'));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_channel_payment_check" CHECK (("lesson_commerce_orders"."channel" = 'pending' and "lesson_commerce_orders"."provider" is null and "lesson_commerce_orders"."payment_intent_id" is null and "lesson_commerce_orders"."payment_method" = 'pending') or ("lesson_commerce_orders"."channel" = 'online' and "lesson_commerce_orders"."provider" is not null and "lesson_commerce_orders"."payment_method" in ('wechat_pay','mock')) or ("lesson_commerce_orders"."channel" = 'offline' and "lesson_commerce_orders"."provider" is null and "lesson_commerce_orders"."payment_intent_id" is null and "lesson_commerce_orders"."payment_method" in ('cash','bank_transfer','wechat_transfer','other')));--> statement-breakpoint
ALTER TABLE "lesson_commerce_orders" ADD CONSTRAINT "lesson_commerce_orders_status_check" CHECK ("lesson_commerce_orders"."status" in ('awaiting_settlement','pending_payment','paid_pending_grant','completed','closed','grant_failed','refunding','refunded'));
